name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  cobertura-file:
    description: Path to the Cobertura XML input file
    required: true
    default: 'coverage/cobertura-coverage.xml'
  output-file:
    description: Path to save the filtered coverage output file
    required: true
    default: 'coverage/cobertura-changed-only.xml'
  main-branch:
    description: Name of the main branch to compare against
    required: false
    default: ${{ github.repository_default_branch }}
  github-token:
    description: GitHub token for accessing the repository
    required: true
    default: '${{ secrets.GITHUB_TOKEN }}'
  # Add a current branch input to specify the branch being processed  
  current-branch:
    description: Name of the current branch
    required: false
    # set default to the current branch using GitHub context
    default: '${{ github.ref_name }}'
  file-filters:
    description:
      Comma-separated list of file patterns to include/exclude (e.g.,
      "src/**/*.ts,!**/*.test.ts")
    required: false
    default: '**/*.*'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
