name: Continuous Integration Release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Github setup
        if: always()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Bundle
        run: |
          npm run bundle

      - name: Run Cobertura Filter Action
        id: coverage
        if: ${{ always() }}
        uses: ZeroWiggliness/CodeCoverageAdv@v1
        with:
          cobertura-file: coverage/cobertura-coverage.xml
          output-file: coverage/cobertura-changed-only.xml
          main-branch: ${{ github.event.repository.default_branch }}
          github-token: ${{ github.token }}
          file-filters: '**/*.*'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          recreate: true
          header: 'Cobertura Coverage Report'
          message: |
            ${{ steps.coverage.outputs.coverage-badge }} ${{ steps.coverage.outputs.coverage-changes-badge }}
            ${{ steps.coverage.outputs.coverage-markdown }}
            ${{ steps.coverage.outputs.coverage-changes-markdown }}

      - name: Update Coverage Badge in README
        if: always()
        run: |
          BADGE="${{ steps.coverage.outputs.coverage-badge }}"
          README="README.md"
          # Replace existing badge or insert at the top if not found
          if grep -q '!\[Coverage\]' "$README"; then
            sed -i 's|!\[Coverage\](.*)|'"$BADGE"'|' "$README"
          elses
            sed -i '1s|^|'"$BADGE"'\n\n|' "$README"
          fi
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add "$README"
          git add "dist/*.js"
          git commit -m "Update coverage badge in README" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_HEAD_REF} || echo "No changes to push"
