name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      #  with:
      #      fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Run Cobertura Filter Action
        id: cobertura-filter
        # only run this step if the previous step was successful
        if: ${{ success() }}
       # uses: ./
        uses: ZeroWiggliness/CobertureChangeOnly@feature/firstimplementation
        with:
          cobertura-file: coverage/cobertura-coverage.xml
          output-file: coverage/cobertura-changed-only.xml
          main-branch: ${{ github.event.repository.default_branch }}
          github-token: ${{ github.token }}
          current-branch: ${{ github.ref_name }}
          file-filters: '**/*.*'

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
